imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        loaders:
          - templating.loader.filesystem
          - templating.loader.theme_loader
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: "gravity_cms"
    fragments:       ~
    http_method_override: true
    translator: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
      - bootstrap_3_horizontal_layout.html.twig
      - GravityCMSCoreBundle:Form:fields.html.twig
      - GravityFileBundle:Form:fields.html.twig
    globals:
       gravity_menu_manager: @gravity_cms.menu_manager

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
      - GravityCMSCoreBundle
      - FOSUserBundle
      - GravityFileBundle
    filters:
      cssrewrite: ~
      uglifyjs2:
        bin: %kernel.root_dir%/../node_modules/.bin/uglifyjs
      sass:
        bin: %kernel.root_dir%/../bin/sass
      compass:
        bin: %kernel.root_dir%/../bin/compass
        load_paths:
          - %kernel.root_dir%/../web/
          - %kernel.root_dir%/..
        no_line_comments: true
        style:            compressed

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

#        filters:
#            softdeleteable:
#                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
#                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: GravityCMS\CoreBundle\Entity\User
    model_manager_name: default
    group:
        group_class: GravityCMS\CoreBundle\Entity\Group

    from_email:
        address:        registration@andy-thorne.co.uk
        sender_name:    Registration andy-thorne.co.uk

    registration:
        confirmation:
            enabled:    true

fos_rest:
    routing_loader:
        default_format: json
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            'Symfony\Component\Security\Core\Exception\AuthenticationException': 401
            'Symfony\Component\Security\Core\Exception\AccessDeniedException': 403
    serializer:
        serialize_null: true

cmf_routing:
  chain:
    routers_by_id:
      cmf_routing.dynamic_router: 300
      router.default: 200
  dynamic:
    enabled: true
    route_provider_service_id: gravity_cms.routing.route_provider

gravity_cms_core:
  entity_manager: default
  backend_type: orm
  default_editor: ckeditor
  cms:
    admin_path: %gravity_cms.admin_path%

gravity_file:
  styles: ~

liip_imagine:
    loaders:
        default:
            stream:
                wrapper: gravity://%gravity_default_filesystem%/
#    resolvers:
#       default:
#          web_path:
#            web_root: "gravity://%gravity_default_filesystem%/"
    cache: stream
    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        medium:
            quality: 75
            filters:
                relative_resize: { widen: 480 }
        large:
            quality: 90
            filters:
                relative_resize: { widen: 1024 }

# gaufrette bundle
knp_gaufrette:
    adapters:
        public:
            local:
                directory:  %kernel.root_dir%/../web/files
                create:     true

    filesystems:
        public:
            adapter:        public

    stream_wrapper:
        protocol: gravity

# gaufrette extras
k_phoen_gaufrette_extras:
    resolvers:
        public:                 # the filesystem name
            prefix:             # the resolver to use
                path: /files    # and its configuration
