bundles:
  - GravityCMS\NodeBundle\GravityCMSNodeBundle
  - Gravity\CKEditorBundle\GravityCKEditorBundle
  - Gravity\TagBundle\GravityTagBundle
#  - GravityCMS\EditorCKE\EditorCKEModule
#  - GravityCMS\FieldTag\FieldTagModule
